sudo: false
language: erlang
install: true
before_script:
- wget https://s3.amazonaws.com/rebar3/rebar3
- chmod +x rebar3
env: PATH=$PATH:.
script: rebar3 as test do xref, dialyzer, eunit, coveralls send
cache:
  directories:
  - $HOME/.cache/rebar3/
otp_release:
- 19.0
- 18.3
- 18.0
# - 17.5
# - R16B03-1
# - R15B03-1
